"use client";
import React from "react";
import Header from "../components/elements/header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Layout = ({ children }) => {
  const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-grow">{children}</main>
          <footer className="bg-black text-white text-center py-4">
            &copy; {new Date().getFullYear()} Teacher Assistant. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
};

export default Layout;